server:
  port: 8080

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:h2:mem:userdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idpgw.test4mind.com/realms/demo-interview

app:
  security:
    client-id: demo-task

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    it.intesigroup.interview.usermanagement: INFO
